spring:
  cloud:
    config:
      import-check:
        enabled: false
  zipkin:
    enabled: true
    base-url: http://172.21.0.61:9411    

server:
  port: 9195

logging:
  level:
    root: INFO
    com:
      itl: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

eureka:
  instance:
    #hostname: localhost
    hostname: 172.21.0.65
    leaseRenewalIntervalInSeconds: 60
    leaseExpirationDurationInSeconds: 100
  client:
    registerWithEureka: true   #telling the server not to register himself in the service registry
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://172.21.0.65:8761/eureka/
